name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Set JVM Flags
      run: |
        JVM_FLAGS="Xmx1024m - Xms512m -XX:+UseG1GC - XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8"
        echo "JVM_FLAGS=$JVM_FLAGS" >> $GITHUB_ENV
        echo "Using JVM Flags: $JVM_FLAGS" 

    - name: Build and Test with Maven
      timeout-minutes: 15
      env:
        MAVEN_OPTS: ${{ env.JVM.FLAGS }}
      run: |
        echo "Compiling and running tests with the following JVM flags:"
        echo $MAVEN_OPTS
        ./mvnw -B verify

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV
        echo "Code coverage: $coverage%" # Log the coverage value

    - name: Fail if coverage has not improved.
      run: |
        coverage=$COVERAGE
        threshold=24.46
        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
          echo "Coverage is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi
